### ISSUE TITLE
Error trying to add articles

### ISSUE THREAD

**Issue by rsilvr** [freshreader/core#51]
I verified that while trying to add articles with encoded characters in the URL I always get the error message "There was an issue saving this URL".

e.g: https://www.nexojornal.com.br/expresso/2020/04/09/A-confiss%C3%A3o-da-Ecovias-sobre-contratos-com-o-governo-paulista

Other that, I'm really appreciating this application and I couldn't find any other issues. Thank you for sharing it.

**Comment by maximevaillancourt** [comment]
Hello Ricardo, thanks for letting me know, I appreciate it.

The issue is now fixed on https://freshreader.app. Let me know if I can help in any other way.

Stay safe! 🙂 

---

![image](https://user-images.githubusercontent.com/8457808/80370502-44c0a280-885e-11ea-898c-1b44ace92fe8.png)
