### ISSUE TITLE
Issue trying to save YouTube URLs

### ISSUE THREAD

**Issue by rsilvr** [freshreader/core#53]
I found this very specific issue trying to save YouTube links. I get the "There was an issue saving this URL." error with both short and long formats:

https://www.youtube.com/watch?v=ACS_azSXxsY
https://youtu.be/xzrh5uuOLtY

And thanks again for this project!

**Comment by maximevaillancourt** [comment]
Hey Ricardo, I suspect the application in production was stuck on a previous revision. I updated it, and it now seems to work on my end.

Could you try again and let me know if it now works as expected?

**Comment by rsilvr** [comment]
It's working now! Thank you.
The only caveat it seems these YouTube links aren't saved with the video title... The stick with just "YouTube" as title

**Comment by maximevaillancourt** [comment]
Now fixed with https://github.com/freshreader/core/pull/56. 🙂 

Thanks again!
