### ISSUE TITLE
Error trying to save non-HTTPS article

### ISSUE THREAD

**Issue by rsilvr** [freshreader/core#62]
While trying to save this article I got the error **"There was an issue saving this URL: SSL_connect returned=1 errno=0 state=error: wrong version number."**

http://www.cs.utexas.edu/users/EWD/transcriptions/EWD03xx/EWD340.html

Although I wouldn't mind if this is a restriction by design because of security reasons. Nowadays it's very rare to find a page like this. In that case maybe a friendly error message would help?

**Comment by maximevaillancourt** [comment]
Thanks for the bug report Ricardo, I appreciate it.

I fixed this in https://github.com/freshreader/core/pull/63.

Cheers!
